// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9R68Asyo9lxDLwehK2vJKBP1rNCRBeU',
    appId: '1:485242111693:web:99a2fa15dd09c2d2b4cb84',
    messagingSenderId: '485242111693',
    projectId: 'foralldin',
    authDomain: 'foralldin.firebaseapp.com',
    storageBucket: 'foralldin.firebasestorage.app',
    measurementId: 'G-EDKW0C8PDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeOfTGmZg2BFZJoA2qmIvDlCDYefe8sRM',
    appId: '1:485242111693:android:bc2260b2849244a5b4cb84',
    messagingSenderId: '485242111693',
    projectId: 'foralldin',
    storageBucket: 'foralldin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0zXotOdWJpOYUUk9CH5zVdXnRR9QJpuY',
    appId: '1:485242111693:ios:2e34ee6c8784c524b4cb84',
    messagingSenderId: '485242111693',
    projectId: 'foralldin',
    storageBucket: 'foralldin.firebasestorage.app',
    iosClientId: '485242111693-m5ih1hrkb56r24vuqpt92mh456s6ilrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.maceVerseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0zXotOdWJpOYUUk9CH5zVdXnRR9QJpuY',
    appId: '1:485242111693:ios:2e34ee6c8784c524b4cb84',
    messagingSenderId: '485242111693',
    projectId: 'foralldin',
    storageBucket: 'foralldin.firebasestorage.app',
    iosClientId: '485242111693-m5ih1hrkb56r24vuqpt92mh456s6ilrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.maceVerseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk9R68Asyo9lxDLwehK2vJKBP1rNCRBeU',
    appId: '1:485242111693:web:384eb5557227c6fbb4cb84',
    messagingSenderId: '485242111693',
    projectId: 'foralldin',
    authDomain: 'foralldin.firebaseapp.com',
    storageBucket: 'foralldin.firebasestorage.app',
    measurementId: 'G-WT1JN30DGS',
  );
}
